### ISSUE TITLE
Have route() return the mapped functions result

### ISSUE THREAD

**Issue by maxfrigge** [christianalfoni/url-mapper#13]
Wouldn't it make sense to have `route()` return the route functions result rather the the url - or false if no route was found.

That way you could do something like

```
mainView(url) {
  return route(url, {
    '/:appId/dash': () => <DashboardContainer props={this.props} />,
    '/:appId/setup': () => <SetupContainer props={this.props} />
  })
}
```

Or is this approach completely nuts anyway and there is a better way of doing this?

**Comment by maxfrigge** [comment]
Discussion should continue in #14

**Comment by Guria** [comment]
We have a plans to return something like 

``` js
{
  callback,
  params
}
```

So who uses urlMapper will decide what args provide to function and would be able to store function return value.

**Comment by maxfrigge** [comment]
Sorry.. I don't really get it. Do you mean that I can define a route and instead of a callback I set an object, which configures the callback and params that get passed to it? Or params that get returned by the call to `route()`?

**Comment by Guria** [comment]
See preview version: https://github.com/Guria/url-mapper/tree/0.5.0

**Comment by Guria** [comment]
See new proposal for 0.5.0 in #15

**Comment by maxfrigge** [comment]
Thanks @Guria looks very straight forward!

**Comment by Guria** [comment]
@maxfrigge please see updated proposal
