### ISSUE TITLE
suggested urlMapper api

### ISSUE THREAD

**Issue by Guria** [christianalfoni/url-mapper#15]
``` js
urlMapper.parse('/bar?bar=baz#hash', '/:foo'); // => { params: { foo: 'bar' }, query: { bar: 'baz' }, hash: 'hash' }
urlMapper.stringify('/:foo', { params: { foo: 'bar' }, query: { bar: 'baz' }, hash: 'hash' }); // => '/bar?bar=baz#hash'
urlMapper.map('/bar?bar=baz#hash', routes, function(match, values){
  match({ route: values })
  return 'some return value';
}); // => 'some return value'
urlMapper.map('/bar?bar=baz#hash', routes); // => { match, values }

```

I have plans to implement this api for next version of lib. Any suggestions?

**Comment by itaylor** [comment]
So in the above, on the third line, values is an object that is the output of urlMapper.parse, containing three properties:
`{ params: { foo: 'bar' }, query: { bar: 'baz' }, hash: 'hash' }`
and `match` is whatever the right hand side of the matched route from `routes` was, correct?

If so, then I'm understanding it right and it looks good to me.

**Comment by Guria** [comment]
Yes, you are completely right.

**Comment by Guria** [comment]
wip here: https://github.com/christianalfoni/url-mapper/tree/next

**Comment by christianalfoni** [comment]
I think this looks really good! I still think we should remove the callback version. I think it adds confusion like: "What is the difference on the callback version and the other version? Is the callback version async? Where is the error?". Yeah, 

``` js
urlMapper.parse('/bar?bar=baz#hash', '/:foo'); // => { params: { foo: 'bar' }, query: { bar: 'baz' }, hash: 'hash' }
urlMapper.stringify('/:foo', { params: { foo: 'bar' }, query: { bar: 'baz' }, hash: 'hash' }); // => '/bar?bar=baz#hash'
urlMapper.map('/bar?bar=baz#hash', routes); // => { match, params, query, hash }
```

This is sooooo clean :-)  "route, target, value, match"... I like route, though I acknowledge people look at it differently. Match is nice too :)

**Comment by Guria** [comment]
Guys I thought a lot about api again.
And I have new proposal which is slight different.
I was bothered a lot on query/hash parts and how we would map it to/from signal parameters.

In fact all we need is stringifying/parsing back from/to any object, like:

``` js
var values = {foo: 'bar', bar: { baz: 'foo', foo: ['foo', 'bar', 'baz'] }};
test.deepEqual(urlMapper.parse('/:foo', urlMapper.stringify('/:foo', values)), values);
```

There is no params, queries and hashes. In `cerebral-router` (or any other lib) we'll just provide route and signal inputs and will get back url or restore signal inputs from url.
It will also allow keep signal clean without any chance to affect signal execution:

``` js
// action to inject
function setUrl (input, state, output, services) {
  state.set(urlStorePath, services.router.getUrl(input));
}
```

About stringifying. I plan to stick next scheme by default:
- substitute keys defined in path from object using `path-to-regexp`'s compile method. Allow only string values for such keys (so we can gurantee that parsed value will remain the same type)
- stringify all left keys with [`URLON` library](https://github.com/vjeux/URLON) which supports any JSON serialazable

``` js
var values = {foo: 'bar', bar: { foo: true, bar: 2, baz: ['foo', 'bar', 'baz'], e:''}};
urlMapper.stringify('/:foo', values); // => '/bar?_bar_foo:true&bar:2&baz@=foo&=bar&=baz;&e='
```

Therefore developer could override stringify/parse with own implementation. The only limit is `parse(stringify(object)) === object`.

I have updated [wip branch](https://github.com/christianalfoni/url-mapper/tree/next) with draft for new implementation

**Comment by christianalfoni** [comment]
Okay, just to make sure I understand this, you want:

``` js
Router(controller, {
  '/:foo/:bar': 'someSignal'
});
```

To give the input to that signal as:

``` js
// url: /hey/ho
{
  foo: 'hey',
  bar: 'ho'
}
```

I really like this concept. Though what about queries? How does the developer access queries? Or are you suggesting limiting the scope? Or, hm, could you explain it from the perspective of implementing a route in Cerebral? :-) I get a bit lost, sorry, hehe

**Comment by Guria** [comment]
@christianalfoni See part after `"About stringifying. I plan to stick next scheme by default:"`

``` js
Router(controller, {
  '/:foo/:bar': 'someSignal'
});
```

``` js
// url: /hey/ho?_baz=:true
{
  foo: 'hey',
  bar: 'ho',
  baz: true
}
```

Anything not in path params stringified to query with `URLON`

---

btw, I can't see your confusion with callback.

``` js
var routeMatched = urlMapper.map(url, routes, function (signal, values) {
  signal(values);
  return true;
});
if (!routeMatched) console.warn('nothing matched');
```

vs

``` js
// es5
var result = urlMapper.map(url, routes);
if (result) {
  result.match(result.values);
} else {
  console.warn('nothing matched');
}
```

**Comment by maxfrigge** [comment]
Very powerful.. but users will have to understand URLON first to understand what's happening.

**Comment by Guria** [comment]
@maxfrigge By users do you mean developers or end users?

**Comment by maxfrigge** [comment]
And you have to be aware that param vars should never have the same name as query params.. which would be new.

**Comment by christianalfoni** [comment]
Aha, I see. URLON seems very powerful, though it requires you to learn URLON to use queries with Cerebral. What does URLON do with normal queries? Just uses strings? `/hey/ho?baz=foo`. Will this become: `{foo: 'hey', bar: 'ho', baz: 'foo'}`?

If it converts normal queries to strings I am all for it, but not if you have to understand URLON completely to start using queries :)

**Comment by maxfrigge** [comment]
@Guria Yes.. developers would be a better name :)

**Comment by Guria** [comment]
@christianalfoni `'/hey/ho?_baz=foo'` <==> `{foo: 'hey', bar: 'ho', baz: 'foo'}`

**Comment by christianalfoni** [comment]
About callback, it is about familiarity. I have never seen a library with this kind of signature:

``` js
var routeMatched = urlMapper.map(url, routes, function (signal, values) {
  signal(values);
  return true;
});
routeMatched // true
```

Callbacks are not typically used to return a value synchronously. Also returning a value seems unnecessary as the callback is only fired if there actually is a match.

``` js
var routeMatched = urlMapper.map(url, routes);
routeMatched // {match, params}
```

The callback does not give any extra value as I see it, just gives a more complex signature.

**Comment by christianalfoni** [comment]
Cool! Then I am all up for URLON, as we can extend normal query use. Awesome stuff! :)

**Comment by Guria** [comment]
@christianalfoni  did you have noticed an underscore?

**Comment by christianalfoni** [comment]
Yeah, so: `?_baz=:true` gives `{baz: true}` and `?baz=true` gives `{baz: 'true'}`, right? :-)

**Comment by maxfrigge** [comment]
Well if it's backwards compatible it would be really cool to have the option to use it - otherwise I would say it's better to leave it up to the developer to choose which implementation to use for parse/stringify.

Another thing to think about is.. should a developer deal with search patters or just with route definitions and the data that goes in and out.

**Comment by Guria** [comment]
> And you have to be aware that param vars should never have the same name as query params

developers wouldn't aware on `urls` at all. there is only signal input and stringified representation

**Comment by Guria** [comment]
@maxfrigge We assume that developer will never construct and use urls by hands. He just calls `controller.signals.smthHapenned.getUrl({})` and gets url. Or just uses ready `<Link>` component from `cerebral-react`

**Comment by maxfrigge** [comment]
@Guria I was referring to the route definition. If you define route `/:foo/bar` and the have a url `/hello/bar?foo=123` you could not merge the search params and path params into a single object.

**Comment by Guria** [comment]
why you have such url? where it came from?

**Comment by christianalfoni** [comment]
Ah, yes, I see your point @maxfrigge. That is a gotcha, but the simplification achieved here is pretty amazing. So I would just avoid that. It is an extreme edge case I would say :-)

@Guria If param name is same as query name it would be overridden on the input

**Comment by maxfrigge** [comment]
@Guria Got it :) You would never have that URL because you wouldn't be able to create an object that would create such a result on stringify - right?

**Comment by Guria** [comment]
@maxfrigge exactly

**Comment by maxfrigge** [comment]
I think it's pretty cool then. Just don't bother with what the address bar "displays" and look at it as some sort of transport protocol for what you are expressing with your code.

**Comment by christianalfoni** [comment]
I suppose with the example: `/:foo/bar` used with  `/hello/bar?foo=123`, the result would just be: `{foo: '123', bar: 'bar'}` , no errors?

But if you are missing the query/param you should be able to debug it very easily I think :-)

**Comment by maxfrigge** [comment]
@christianalfoni The url `/hello/bar?foo=123` could only be created by hand.. it would be impossible with the stringify implementation.

**Comment by Guria** [comment]
@christianalfoni 

> Yeah, so: ?_baz=:true gives {baz: true} and ?baz=true gives {baz: 'true'}, right? :-)

Nope. Here it is right: 
- `?_foo:true&bar=baz` <==> `{ foo: true, bar: 'baz' }`
- `?_foo=true&bar=baz` <==> `{ foo: 'true', bar: 'baz' }`

But I can do in urlMapper:
- `?foo=true&bar=baz` ==> `{ foo: 'true', bar: 'baz' }` (only parse direction)
- `?_foo=true&bar=baz` <==> `{ foo: 'true', bar: 'baz' }`

**Comment by christianalfoni** [comment]
@maxfrigge Good point :-) But it might happen, maybe a user inserts it. Not sure if needed handling though

@Guria I do not quite understand why `?_foo=true&bar=baz` <==> `{ foo: 'true', bar: 'baz' }`? Is the underscore just a leading underscore? Not for every query you want to parse to JS?

**Comment by maxfrigge** [comment]
I think it just indicates that urlon should to it's thing (e.g. parsing typed values).

So when not having the underscore `?foo=:true` <==> `{ foo: ':true' }` instead `{ foo: true }`

**Comment by christianalfoni** [comment]
Yeah, so why do I need underscore when I just want to do normal parsing? :-)

Anyways, I think we all agree that:

`/foo/bar?baz=true` should become `{param1: 'foo', param2: 'bar', baz: 'true'}`

and

`/foo/bar?_baz:true` should become `{param1: 'foo', param2: 'bar', baz: true}`

Then I am happy :-)

**Comment by Guria** [comment]
@christianalfoni underscore means `object`. we can't have properies without object :D

**Comment by Guria** [comment]
> `/foo/bar?baz=true` should become `{param1: 'foo', param2: 'bar', baz: 'true'}`

I'll do it, but: 
`{param1: 'foo', param2: 'bar', baz: 'true'}` will be `/foo/bar?_baz=true`

**Comment by maxfrigge** [comment]
@christianalfoni But as soon as you would stringify `{param1: 'foo', param2: 'bar', baz: 'true'}` urlon would add the underscore - which could be confusing in those cases where developers create the url by hand.

**Comment by maxfrigge** [comment]
I think that URLON is extremely cool, but not sure if it's suited as the default implementation. How about having `url-mapper` as the default implementation and then create `urlon-mapper` as an alternate implementation. If then everyone ditches `url-mapper` you can just make `urlon-mapper` the default implementation at some point.

**Comment by Guria** [comment]
@christianalfoni @maxfrigge
Hmm, I think I can strip first underscore safely. And we'll get `querystring` compatibility for very basic cases

**Comment by Guria** [comment]
I'll secure this with tests, of course

**Comment by christianalfoni** [comment]
Yeah, there is a "must have" for URLON here and that is to make it work just like normal queries both ways. If that is problematic I suggest we use url-mapper as default, but allow to pass mapper:

``` js
Router(controller, routes, {
  mapper: urlonMapper
});
```

This fits very nicely in with your suggestion @Guria. Thinking of it, I think this might be the best way to do it. That way we do not make URLON "special" in Cerebral and the developer makes a conscious choice to use it and it works exactly like the URLON documentation.

How you guys feel about that?

**Comment by Guria** [comment]
@maxfrigge I can offer default implementation with just `path-to-regexp` without special query / hash support. It is the only way to keep it simple `{}` <==> `""` without hardcoding "special" keys in object to map query / hash parts.

**Comment by Guria** [comment]
> `urlonMapper`

it can't be named `urlonMapper` since we use 2 str/parse libs. `path-to-regexp` for path and route matching and `URLON` deals with only query part

**Comment by maxfrigge** [comment]
I agree with christian. It has to be 100% compatible with default query parsing back and forth - otherwise the will be too man wtf moments. 

@Guria Do I understand this right: The default implementation is `path-to-regexp` and urlon would just be an addon for search params?

**Comment by christianalfoni** [comment]
What if we add an option to router then? :-)

``` js
Router(controller, routes, {
  urlon: true
});
```

There? :-)

**Comment by maxfrigge** [comment]
:+1:  Easy enough and developers are not left in the dark about what's happening with their urls.

**Comment by Guria** [comment]
@christianalfoni what you would expect in case of `useUrlon: false`? BTW, I don't like it at all at least because it can't be router option.

**Comment by Guria** [comment]
Guys, My offer is stick to urlon but make it compatible with familiar qs format (but without nesting, arrays, etc)

**Comment by Guria** [comment]
I'll do
`{ foo: 'bar', bar: 'baz'}` <==> `?foo=bar&bar=baz`

**Comment by maxfrigge** [comment]
@Guria Having the one ring to rule the all option would be cool. 
How would you handle `{foo: true}` or `{foo: [1,2]}`?

Maybe we should start with use cases before jumping in on it.

**Comment by Guria** [comment]
But `{ foo: { bar: 'baz' }}` would be stringified to `'foo_bar=baz'`

**Comment by maxfrigge** [comment]
@Guria That's cool because it doesn't really exist in default qs parsing

**Comment by Guria** [comment]
@maxfrigge I woldn't handle it at all. it already handled by `URLON` but not handled properly by `qs`

**Comment by Guria** [comment]
just do `npm i vjeux/URLON` and try it in node REPL or see examples in docs

**Comment by Guria** [comment]
My point is that `qs` could not guarantee `parse(stringify(object)) === object`. That why I don't want to provide it as default. Developer would have to make complicated checks and type conversions in actions.

With `path-to-regexp` we still sticked to `string` only values(can be workarounded I think, but now I suggest just accept this limit). But `URLON` unlockes to have support to anything that can be provided to signal.

**Comment by Guria** [comment]
BTW, I made `url-mapper` a factory, so it's behavior could be tweaked with options:

``` js
Router(controller, routes, {
  mapper: urlMapper(mapperOptions)
});
```

It may contain configuration for `path-to-regexp`, for example. Or even redefine [`compileRoute` function](https://github.com/christianalfoni/url-mapper/blob/f8bea2970436c50e1afdd8da850ef8c5fa4e7eaa/index.js#L10)

**Comment by maxfrigge** [comment]
@Guria I get your point about type conversion, which is a plus for actions but it's adding complexity to the urls. If it was up to me I wouldn't mind it at all, but it could be irritating to others when suddenly they see a url pattern in their browser, which they don't understand. 

All I am saying is that you have to be aware of what's going on and most developers are used to `?list[]=1&list[]=2` rather then `list@:1&:2` - even though I would prefer the latter when you take it's benefits into account.

**Comment by maxfrigge** [comment]
:+1: for the factory - very clean!

**Comment by Guria** [comment]
For end user `list[]=1&list[]=2` and `list@:1&:2` would be equally meaningless except he is a geek.
Absolutely most users never look at addressbar at all.

What user cares in fact is working and bugless behavior of app helping him to do some bussiness. If user tries to manipulate an url that a signal that app has UX problems.

**Comment by maxfrigge** [comment]
@Guria Sorry - I was referring to developers again :)

**Comment by maxfrigge** [comment]
Why not make it optional in the beginning and see how developers react to it?

**Comment by christianalfoni** [comment]
Okay, this is a tough one... 
1. Really good to just handle params/queries transparently with an input object
2. Good to empower developers to make queries be more than just queries, they can be actual JS objects to do all sorts of crazy inputs on signals by just using a url
3. Not good to change default look of queries. It will be off putting to developers

So we need to solve the third point here:
1. Do we tell developers that we have chosen to use `urlon` to empower them. That they should stop focusing on the url itself, just think about objects that gets passed to signals, the url is just a sideeffect
2. Do we implement a way to toggle it on/off some way

The best approach is to make it optional, but if it creates a lot of implementation difficulties we can still consider option 1 here. It only affects queries, which is not very common to use, but could be extremely common as we empower them using Cerebral router

**Comment by Guria** [comment]
As for today `cerebral-router` doesn't have good support for queries. It parsed with `qs` and exposed as meta to action input. There is nor auto mapping signal inputs to query, nor easy and clean way to `signal.getUrl()` with queries and hashes.
I don't want to ship semi-functional support now when I achieved a lot in splitting responsibilities between libs.

The only safe default I can suggest is ignore query / hash (as it now, but even do not provide it as meta) at all. Developer still be able to parse querystring by accessing `store.get(urlStorePath)`, but will not able get url with queries from signal call (as it now).
And allow to opt-in with full featured query support.

**Comment by christianalfoni** [comment]
So in other words:

Lets move ahead with @Guria implementation, but you have to opt-in on parsing queries using urlon? Which will be full fledged urlon queries.

You can still fall back to manually parsing queries however you want by grabbing the current url from the store.

Am I understanding this correctly?

**Comment by Guria** [comment]
Indeed

**Comment by christianalfoni** [comment]
Okay, would you mind summarizing this in API examples @Guria? Just to have lika a conclusion on all the discussion? :-)

So:
1. Example of how you set up the router without urlon queries
2. Example of how to parse query strings if needed
3. Example of how you set up the router with urlon queries support
4. Example of how those queries are parsed/stringified

**Comment by maxfrigge** [comment]
:+1 Let me know if you want me to help

**Comment by Guria** [comment]
@christianalfoni 

> Example of how you set up the router without urlon queries

``` js
Router(controller, routes, {
  mapper: urlMapper()
});
```

upd due @maxfrigge comment:

``` js
Router(controller, routes);
```

> Example of how to parse query strings if needed

``` js
// dev exposes `qs` as a service
function (input, state, output, { qs }) {
  var queryString = state.get(['url']).split(/\?(.+)/)[1];
  var query = qs.parse(queryString);
}
```

> Example of how you set up the router with urlon queries support

``` js
Router(controller, routes, {
  mapper: urlMapper({
    query: true
  })
});
```

upd due @maxfrigge comment:

``` js
Router(controller, routes, {
  mapper: { query: true }
});
// or custom mapper:
Router(controller, routes, {
  mapper: { parse: function(){}, stringify: function(){}, map: function(){} }
});
```

> Example of how those queries are parsed/stringified

for `/:param` route:
`{ param: 'path', foo: 'bar', bar: 'true', baz: '2'}` <==> `'/path?foo=bar&bar=true&baz=2'`
`{ param: 'path', foo: 'bar', bar: true, baz: 2}` <==> `'/path?foo=bar&bar:true&baz:2'`
`{ param: 'path', foo: 'bar', bar: 'true', baz: '2', object: { array: ['string', 2, true, { foo: 'bar'}] }}` <==> `'/path?foo=bar&bar=true&baz=2&object_array@=string&:2&:true&_foo=bar'`

**Comment by christianalfoni** [comment]
Okay, cool, 

So I think this looks really great! What I would like though is to include the urlMapper inside `cerebral-router`, but still allow you to override it using the mapper property. The reason is that 99% use cases will be using the urlMapper. Requiring two different dependencies to do routing will be off putting. This way we do not break any current code and we still allow flexibility in using other mappers.

So:

``` js
Router(controller, routes, {
  query: true
});

// My custom mapper
Router(controller, routes, {
  mapper: SomeMapper({})
});
```

Does that make sense?

**Comment by maxfrigge** [comment]
How about:

```
Router(controller, routes, {
  mapper: { query: true }
});
```

Passing a plain object will configure the default mapper - passing an object that has mapper interface methods will replace the default mapper.

**Comment by christianalfoni** [comment]
That works for me too :-)

**Comment by Guria** [comment]
@maxfrigge :+1: good one, will use it

**Comment by Guria** [comment]
examples updated

**Comment by christianalfoni** [comment]
Cool! I like this! :+1:  :-)

**Comment by Guria** [comment]
@christianalfoni what about to preserve `map` signature with callback, but just don't do return from callback that confuses you?

**Comment by Guria** [comment]
@christianalfoni also want to add matched route to callback parameters / return object:

``` js
var routeMatched = false;

urlMapper.map(url, routes, function (signal, values, route) {
  signal(values);
  routeMatched =  true;
});

if (!routeMatched) console.warn('nothing matched');
```

and

``` js
urlMapper.map(url, routes);
// => {match: function(){}, values: {foo: 'bar'}, route: '/:foo'}
```

**Comment by christianalfoni** [comment]
Hehe, I am going to be a real shit about this, I do not think we should include callback signature :-)
1. The developer has to learn two different signatures that does the exact same thing
2. The developer will ask... what is the difference? There is a callback, is it async? Why is it async?
3. The callback does not add any value. There is nothing you can do with the callback that you can not do with a normal sync signature

But this is not a big issue of course. If you still feel it is worth it, please implement, but I just do not think it gives any value, only confusion ;-)

**Comment by Guria** [comment]
~~I understand your point. Just don't like how it would be ugly in es5 code:~~

``` js
var routeMatched = false;

(function(result){
  result.match(result.values);
  routeMatched =  true;
})(urlMapper.map(url, routes));

if (!routeMatched) console.warn('nothing matched');
```

~~or~~ looked closer, seems this one pretty good:

``` js
var result = urlMapper.map(url, routes);

if (result) {
  result.match(result.values);
} else {
  console.warn('nothing matched');
}
```

What about `route` in return values? So:

``` js
{
  route: '/:foo',       // key from routes
  match: function(){},  // value (signal, component, whatever) from routes
  values: {foo: 'bar'}  // parsed values from route
}
```

**Comment by christianalfoni** [comment]
Love it! :+1: :)

**Comment by itaylor** [comment]
:+1:  
I like where this landed.  It's cool that the `match` doesn't have to be a function anymore, instead the implementor gets to decide how best to use the match in their code, and `urlMapper` is just responsible for figuring out which url matched.

**Comment by Guria** [comment]
I have splitted compileRoute and mapper itself so we'll have:
- `require('url-mapper')()` - mapper with path-to-regexp without queries
- `require('url-mapper')({ query: true})` - mapper with path-to-regexp with URLON queries
- `require('url-mapper')({ compileFn })` - mapper with redefined custom compileFn:

``` js
require('url-mapper')({ 
  key: 'would be passed to compileFn in options',
  compileFn: (route, options, cache) => { 
    return { parse, stringify } 
  }
})
```
- `require('url-mapper/mapper')(compileFn, options)` - mapper with redefined custom compileFn:

``` js
require('url-mapper/mapper')({ 
  (route, options, cache) => { 
    return { parse, stringify } 
  },
  optionsForCompileFn
})
```

**Comment by Guria** [comment]
Therefore developer can provide custom `compileFn(route, options, cache)` function that returns methods `parse(url)` and `stringify(object)`

**Comment by Guria** [comment]
3rd and 4th bullets in latest list is about the same. So I decided not to support `require('url-mapper')({ compileFn })` because it will leave unused refs to default `compileFn` with its deps (path-to-regexp, URLON). One who want make custom mapper should use clean variant `require('url-mapper/mapper')(compileFn, options)`

**Comment by maxfrigge** [comment]
@Guria Makes sense. I would prefer to have one clean way too. I haven't however seen much of the url-mapper code to understand all the details :)

**Comment by Guria** [comment]
wip in `next` branch

**Comment by Guria** [comment]
ready with 100% coverage.
see tests for details.
next steps:
- [x] update README
- [ ] resolve review comments
- [x] check that new version fits for `cerebral-router` and `cerebral-state-router`
- [ ] publish to npm

**Comment by christianalfoni** [comment]
Awesome job @Guria! I think it is wise to drop the last point, as you say. I really like the principle of having one flexible way of doing it, rather than multiple ways for certain scenarios. Looking forward to its release :)

**Comment by Guria** [comment]
Ok. I have updated [README](https://github.com/christianalfoni/url-mapper/pull/16/files#diff-04c6e90faac2675aa89e2176d2eec7d8R1). Would be great to get review on it and check spelling. I am not native speaker, you know :)

**Comment by itaylor** [comment]
I ported over itaylor/redux-action-router to the new API.  It simplified my code considerably.  :+1: 

```
$ git diff --stat src/index.js 
 src/index.js | 66 ++++++++++++++++++++++++------------------------------------
 1 file changed, 26 insertions(+), 40 deletions(-)
```
