### ISSUE TITLE
Uncaught ReferenceError: URLON is not defined

### ISSUE THREAD

**Issue by bobiblazeski** [christianalfoni/url-mapper#18]
Since reactive router is depreciated I would like to replace with url-mapper.
However as soon as require url-mapper I get this error in the console.
var  Mapper = require('url-mapper');

Uncaught ReferenceError: URLON is not defined

**Comment by Guria** [comment]
Please try to remove your `node_modules` folder and then `npm i` again.

**Comment by bobiblazeski** [comment]
Same error
main.js:52077 Uncaught ReferenceError: URLON is not defined

**Comment by christianalfoni** [comment]
@bobiblazeski Are you running it through some transpiler? Make sure you do not run node_modules folder through the transpiler. If not, what setup do you use? webpack?

**Comment by bobiblazeski** [comment]
I'm using webpack, babel & uglify

```
var webpack = require('webpack');
var rupture = require('rupture');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var stylusLoader = ExtractTextPlugin.extract("style-loader", "css-loader!stylus-loader");

module.exports = {
  entry: './client/client.js',
  output: {
    path: __dirname + '/public/app',
    filename: "[name].js"
  },
  module: {
    loaders: [{
      test: /\.js$/,
      exclude: /node_modules/,
      loader: 'babel-loader'
    }, {
      test: /\.styl$/,
      loader: stylusLoader
    }, {
      test: /\.css$/,
      loader: stylusLoader
    }, {
      test: /\.json$/,
      loader: 'json-loader'
    }]
  },
  stylus: {
    use: [rupture()]
  },
  plugins: [new ExtractTextPlugin("[name].css")]
    .concat(process.env.NODE_ENV === 'production' ? [new webpack.optimize.UglifyJsPlugin({
      minimize: true
    })] : []),
  externals: {},
  resolve: {
    extensions: ['', '.js', '.jsx', '.styl', '.css']
  }
};
```

Added
  exclude: /node_modules/, to babel loader no effect at all

**Comment by bobiblazeski** [comment]
Solved: 
exclude: /node_modules/  helped  after I restarted the watch process to use the config that includes that line.

Many thanks @christianalfoni

**Comment by christianalfoni** [comment]
:+1:
