### ISSUE TITLE
Documentation example: urlMapper is not a function

### ISSUE THREAD

**Issue by bobiblazeski** [christianalfoni/url-mapper#19]
```
const urlMapper = Mapper();

var matchedRoute = urlMapper('/bar/baz/:42',
```

urlMapper is not a function.

```
I believe it should urlMapper.map('/bar/baz/:42', ...
```

**Comment by christianalfoni** [comment]
I will let @Guria answer this one :-)

**Comment by bobiblazeski** [comment]
BTW I'm still using the require syntax

```
 var Mapper = require('url-mapper');
var urlMapper = Mapper();
var matchedRoute = urlMapper.map(....

```

**Comment by Guria** [comment]
Will check and fix as soon will be at pc

**Comment by Guria** [comment]
@bobiblazeski It very strange since default export is fubction in fact. just check out https://tonicdev.com/npm/url-mapper

**Comment by Guria** [comment]
You are completely right. Will fix it now :)
