### ISSUE TITLE
Make It Possible To Pass Options To pathToRegexp object

### ISSUE THREAD

**Issue by lots0logs** [christianalfoni/url-mapper#29]
Currently it doesn't appear to be possible to pass options from Cerebral router to the pathToRegexp object. I'd like to set `strict` to `false` so that urls with trailing slashes will match patterns that don't have a trailing slash. If there is another way to accomplish this please let me know.

**Comment by Guria** [comment]
Hello, sorry for late response.
It seems that `false` is already default value for `strict` option according to path-to-regex docs.

Anyway I am not ready to add passing options now, though you can copy `compileRoute.js` file into your project and apply any customization you want. Then you can [make your mapper](https://github.com/cerebral/url-mapper#matcher):
```js
import urlMapper from 'url-mapper'
import myCompileFn from './my-compileRoute'
export default urlMapper(myCompileFn, options);
```

Cerebral Router has base version that you can pass your custom mapper:
```js
import myUrlMapper from './my-url-mapper'
import baseRouter from '@cerebral/router/base'

export default function myRouter (options = {}) {
  return baseRouter(Object.assign(options, { mapper: myUrlMapper }))
}
```

**Comment by lots0logs** [comment]
@Guria Thanks for the tip, much appreciated! :smiley:
