### ISSUE TITLE
Replace wildcard routes with actual path.

### ISSUE THREAD

**Issue by jeroenverfallie** [christianalfoni/url-mapper#4]
When using a wildcard route at the end of cerebral-router, to catch 404’s, it’s also replacing the url with /\* in the urlbar.

It should replace with the actual matched url.

**Comment by Guria** [comment]
pretty sure it fixed in `cerebral-router`
https://github.com/christianalfoni/cerebral-router/blob/master/tests/test.js#L210-L226
